<a href="https://colab.research.google.com/github/Sepren/MachineLearning/blob/main/%D0%A3%D0%BF%D1%80%D0%B0%D0%B6%D0%BD%D0%B5%D0%BD%D0%B8%D1%8F.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from IPython.core.display import HTML
HTML("""
<style>

div.cell { /* Tunes the space between cells */
margin-top:1em;
margin-bottom:1em;
}

div.text_cell_render h1 { /* Main titles bigger, centered */
font-size: 2.2em;
line-height:1.4em;
text-align:center;
}

div.text_cell_render h2 { /*  Parts names nearer from text */
margin-bottom: -0.4em;
}


div.text_cell_render { /* Customize text cells */
font-family: 'Times New Roman';
font-size:1.5em;
line-height:1.4em;
padding-left:3em;
padding-right:3em;
}
</style>
""")

# Упражнения

### NUMPY

<img src='../../../img/trainings1.jpg'/>

1) Импортировать `NumPy` под именем `np`

In [3]:
import numpy as np

2) Напечатать версию и конфигурацию

In [7]:
!pwd
!ls

/content
sample_data


3) Создайте нулевой вектор размером 10

In [8]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

4) Создать вектор размера 10, заполненный единицами

In [9]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

5) Создать вектор размера 10, заполненный нулями, но пятый элемент равен 1

In [12]:
a = np.zeros(10)
a[4] = 1
a

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

6) Создать вектор со значениями от 10 до 49

In [18]:
a = np.linspace(10, 49, 40)
a

array([10., 11., 12., 13., 14., 15., 16., 17., 18., 19., 20., 21., 22.,
       23., 24., 25., 26., 27., 28., 29., 30., 31., 32., 33., 34., 35.,
       36., 37., 38., 39., 40., 41., 42., 43., 44., 45., 46., 47., 48.,
       49.])

7) Создать и потом развернуть вектор (так, чтобы первый элемент стал последним)

In [19]:
a = np.linspace(10, 49, 40)
a[::-1]

array([49., 48., 47., 46., 45., 44., 43., 42., 41., 40., 39., 38., 37.,
       36., 35., 34., 33., 32., 31., 30., 29., 28., 27., 26., 25., 24.,
       23., 22., 21., 20., 19., 18., 17., 16., 15., 14., 13., 12., 11.,
       10.])

8) Создать матрицу (двумерный массив) 3x3 со значениями от 0 до 8

In [35]:
# A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
# A
A


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

9) Создать 3x3 единичную матрицу

In [36]:
# A = np.arange(1, 9, 9)
n = A.shape
B = A.reshape((1, n))
B

TypeError: ignored

10) Создать массив 3x3x3 со случайными значениями

11) Создать массив 10x10 со случайными значениями, найти минимум и максимум

12) Создать случайный вектор размера 30 и найти среднее значение всех элементов

13) Создать матрицу с 0 внутри, и 1 на границах

In [50]:
A = np.zeros((4, 4))
A[1:3:, 1:3:] = 1
A

array([[0., 0., 0., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 0., 0., 0.]])

14) Создать 8x8 матрицу и заполнить её в шахматном порядке, не используя функцию tile

In [54]:
A = np.zeros((8, 8))
A[::2, 1:8:2] = 1
A[1::2, :8:2] = 1
A

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

15) Создать 8x8 матрицу и заполнить её в шахматном порядке, используя функцию tile

16) Перемножить матрицы размеров 5x3 и 3x2

In [60]:
A = np.array([[1, 2, 3], [4, 3, 2], [7, 6, 5], [1, 2, 3], [1, 2, 3]])
B = np.array([[1, 2], [3, 4], [2, 3]])
C = np.dot(A, B)
C

array([[13, 19],
       [17, 26],
       [35, 53],
       [13, 19],
       [13, 19]])

17) Дан массив, поменять знак у элементов, значения которых между 3 и 8

In [65]:
mask = (C > 12) * (C < 20)
C[mask] = -C[mask]
C

array([[-13, -19],
       [-17,  26],
       [ 35,  53],
       [-13, -19],
       [-13, -19]])

18) Создать 5x5 матрицу со значениями в строках от 0 до 4

In [71]:
A = np.ones((5, 5))
v1 = np.arange(5)
(A * v1).astype(int)

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

19) Создать вектор размера 10 со значениями от 0 до 1, не включая ни то, ни другое

In [77]:
v1 = np.linspace(0, 1, 12)
mask = (v1 != 0) * (v1 != 1)
v1[mask]

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

20) Дан массив 10x2 (точки в декартовой системе координат), преобразовать в полярную

21) Заменить максимальный элемент на ноль

In [76]:
max(v1) = 0
v1

SyntaxError: ignored

22) Из двух массивов сделать матрицу Коши $C (C_{ij} = \frac{1}{x_i - y_j})$

23) Преобразовать массив из float в int

24) Случайно расположить p элементов в 2D массив

25) Отнять среднее из каждой строки в матрице

26) Найти диагональные элементы произведения матриц

27) Дан вектор [1, 2, 3, 4, 5], построить новый вектор с тремя нулями между каждым значением

### Разреженные матрицы

<img src='../../../img/trainings.png'/>

1) Соберите из предложенной таблички csr-матрицу.
Дана таблица посещений пользователями сайтов.
Строки - описание сессий в интернете для пользователей. Польозватели закодированы числами(1-2-3) в столбце target. Сайты закодированы числами от 1 до 11. Нам не важно, что это были за сайты, при этом 0 - это не сайт, а отсутствие данных, когда за сессию было посещено менее 10 сайтов.
Задача - собрать матрицу с частотными описаниями предпочтений пользователей, в которой для каждого сайта указывалось бы, сколько раз пользователь на него вообще заходил за все свои сессии.

Насколько эффективнее sparse матрица будет при количестве разных сайтов 10000? При количестве пользователей 1000?

In [ ]:
import pandas as pd
data = pd.read_csv('../../../data/train_data_3users.csv')
data.drop('session_id', axis=1, inplace=True)

In [ ]:
import scipy.sparse
scipy.sparse.csr_matrix(data.values)

2) Создать 2 случайные матрицы размерами 10х10 с долей ненулевых элементов не более 10% и перемножить в их в csr и numpy формате. Сравнить время

### PANDAS

<img src='../../../img/trainings2.jpg'/>

**В задании предлагается с помощью Pandas ответить на несколько вопросов по данным репозитория UCI [Adult](https://archive.ics.uci.edu/ml/datasets/Adult) (качать данные не надо – они уже есть в репозитории).

Уникальные значения признаков (больше информации по ссылке выше):
- age: continuous.
- workclass: Private, Self-emp-not-inc, Self-emp-inc, Federal-gov, Local-gov, State-gov, Without-pay, Never-worked.
- fnlwgt: continuous.
- education: Bachelors, Some-college, 11th, HS-grad, Prof-school, Assoc-acdm, Assoc-voc, 9th, 7th-8th, 12th, Masters, 1st-4th, 10th, Doctorate, 5th-6th, Preschool.
- education-num: continuous.
- marital-status: Married-civ-spouse, Divorced, Never-married, Separated, Widowed, Married-spouse-absent, Married-AF-spouse.
- occupation: Tech-support, Craft-repair, Other-service, Sales, Exec-managerial, Prof-specialty, Handlers-cleaners, Machine-op-inspct, Adm-clerical, Farming-fishing, Transport-moving, Priv-house-serv, Protective-serv, Armed-Forces.
- relationship: Wife, Own-child, Husband, Not-in-family, Other-relative, Unmarried.
- race: White, Asian-Pac-Islander, Amer-Indian-Eskimo, Other, Black.
- sex: Female, Male.
- capital-gain: continuous.
- capital-loss: continuous.
- hours-per-week: continuous.
- native-country: United-States, Cambodia, England, Puerto-Rico, Canada, Germany, Outlying-US(Guam-USVI-etc), India, Japan, Greece, South, China, Cuba, Iran, Honduras, Philippines, Italy, Poland, Jamaica, Vietnam, Mexico, Portugal, Ireland, France, Dominican-Republic, Laos, Ecuador, Taiwan, Haiti, Columbia, Hungary, Guatemala, Nicaragua, Scotland, Thailand, Yugoslavia, El-Salvador, Trinadad&Tobago, Peru, Hong, Holand-Netherlands.   
- salary: >50K,<=50K

In [78]:
import pandas as pd
# чтоб картинки рисовались в тетрадке
%matplotlib inline
import matplotlib.pyplot as plt
import seaborn as sns
plt.rcParams['figure.figsize'] = (10, 8)

In [79]:
data = pd.read_csv('adult.data.csv')
data.head()

age         workclass  fnlwgt  education  education-num  \
0   39         State-gov   77516  Bachelors             13   
1   50  Self-emp-not-inc   83311  Bachelors             13   
2   38           Private  215646    HS-grad              9   
3   53           Private  234721       11th              7   
4   28           Private  338409  Bachelors             13   

       marital-status         occupation   relationship   race     sex  \
0       Never-married       Adm-clerical  Not-in-family  White    Male   
1  Married-civ-spouse    Exec-managerial        Husband  White    Male   
2            Divorced  Handlers-cleaners  Not-in-family  White    Male   
3  Married-civ-spouse  Handlers-cleaners        Husband  Black    Male   
4  Married-civ-spouse     Prof-specialty           Wife  Black  Female   

   capital-gain  capital-loss  hours-per-week native-country salary  
0          2174             0              40  United-States  <=50K  
1             0             0              13  United-States  <=50K  
2             0             0              40  United-States  <=50K  
3             0             0              40  United-States  <=50K  
4             0             0              40           Cuba  <=50K

1) Сколько мужчин и женщин (признак *sex*) представлено в этом наборе данных?

In [81]:
data["sex"].value_counts()

Male      21790
Female    10771
Name: sex, dtype: int64

2) Каков средний возраст (признак *age*) женщин?

In [94]:
data.groupby('sex')

3) Постройте гистограмму распределения (*bar plot*) образования людей (признак *education*).

4) Каковы средние значения и среднеквадратичные отклонения возраста тех, кто получает более 50K в год (признак *salary*) и тех, кто получает менее 50K в год?

5) Правда ли, что люди, которые получают больше 50k, имеют как минимум высшее образование? (признак *education - Bachelors, Prof-school, Assoc-acdm, Assoc-voc, Masters* или *Doctorate*)

6) Среди кого больше доля зарабатывающих много (>50K): среди женатых или холостых мужчин (признак *marital-status*)? Женатыми считаем тех, у кого *marital-status* начинается с *Married* (Married-civ-spouse, Married-spouse-absent или Married-AF-spouse), остальных считаем холостыми.

7) Посчитайте среднее время работы (*hours-per-week*) зарабатывающих мало и много (*salary*) для каждой страны (*native-country*).

###  Графики

<img src='../../../img/trainings.JPG' width=50%>

## Загрузка и знакомство с данными

Для работы вам понадобятся данные из учебного конкурса на kaggle [«Прогноз популярности статьи на Хабре»](https://inclass.kaggle.com/c/howpop-habrahabr-favs-lognorm). Файл **`howpop_train.csv`** уже лежит в нашем репозитории в каталоге **`data`**.

In [ ]:
df = pd.read_csv('../../../data/howpop_train.csv')

In [ ]:
df.shape

In [ ]:
df.head(3).T

Избавимся сразу от переменных, названия которых заканчиваются на `_lognorm`. Выберем их с помощью `filter()` и удалим `drop`-ом:

In [ ]:
df.drop(filter(lambda c: c.endswith('_lognorm'), df.columns),
        axis = 1,       # axis = 1: столбцы
        inplace = True) # избавляет от необходимости сохранять датасет

In [ ]:
df.describe().T

In [ ]:
df.describe(include = ['object', 'bool'] # бинарные и категориальные переменные
           ).T

In [ ]:
# настройка внешнего вида графиков в seaborn
sns.set_style("dark")
sns.set_palette("RdBu")
sns.set_context("notebook", font_scale = 1.5,
                rc = { "figure.figsize" : (15, 5), "axes.titlesize" : 18 })

Столбец **`published`** (время публикации) содержит строки. Чтобы мы могли работать с этими данными как с датой/временем публикации, приведём их к типу `datetime`:

In [ ]:
print(df.published.dtype)
df['published'] = pd.to_datetime(df.published, yearfirst = True)
print(df.published.dtype)

Создадим несколько столбцов на основе данных о времени публикации:

In [ ]:
df['year'] = [d.year for d in df.published]
df['month'] = [d.month for d in df.published]

df['dayofweek'] = [d.isoweekday() for d in df.published]
df['hour'] = [d.hour for d in df.published]

-----
Теперь Ваша очередь. В каждом пункте предлагается построить картинку и с ее помощью ответить на вопрос. Конечно, можно попытаться ответить на все вопросы только с Pandas, без картинок, но мы будем смотреть на (красивые) визуализации.   

#### 1\. В каком месяце (и какого года) было больше всего публикаций?

* март 2016,
* март 2015,
* апрель 2015,
* апрель 2016.

#### 2\. Проанализируйте публикации в этом месяце (из вопроса 1)

Выберите один или несколько вариантов:

* На графике не заметны какие-либо выбросы или аномалии,
* Один или несколько дней сильно выделяются из общей картины,
* На хабре _всегда_ больше статей, чем на гиктаймсе,
* По субботам на гиктаймс и на хабрахабр публикуют примерно одинаковое число статей.

Подсказки: постройте график зависимости числа публикаций от дня; используйте параметр `hue`

#### 3\. Выберите верное утверждение

* Больше всего просмотров (в среднем) набирают статьи, опубликованные в 12 часов дня;
* У опубликованных в 10 утра постов больше всего комментариев  (в среднем);
* Больше всего просмотров  (в среднем) набирают статьи, опубликованные в 6 часов утра;
* Максимальное число комментариев на гиктаймсе набрала статья, опубликованная в 9 часов вечера;
* На хабре дневные статьи комментируют чаще  (в среднем), чем вечерние.

#### 4\. Кого из топ-20 авторов (по числу статей) чаще всего минусуют (в среднем)?

* @Mordatyj
* @Mithgol
* @alizar
* @ilya42

#### 5\. Сравните субботы и понедельники

Правда ли, что по субботам авторы пишут в основном днём, а по понедельникам — в основном вечером?